<?php

// Implements hook_block_info().
function custom_2_block_info() {
  $blocks = array();
  $blocks['my_block'] = array(
    'info' => t('My Custom Block'),
  );

  return $blocks;
}

// Implements hook_block_configure().
function custom_2_block_configure($delta = '') {
  $form = array();
  if ($delta == 'my_block') {
    $form['text_body'] = array(
      '#type' => 'text_format',
      '#title' => t('Enter your text here in WYSIWYG format'),
      '#default_value' => variable_get('text_variable', ''),
    );
  }
}
