<?php

function custom_block_2_help($path, $arg) {
  switch ($path) {
    case "admin/help#custom_block":
      return '' . t('This is my 2nd custom block') . '';
      break;
  }
}

function custom_block_2_block_info() {
  $blocks['custom_block_2'] = array (
    'info' => t('Current posts'), 
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

function custom_block_2_block_view($delta = '') {
  switch ($delta) {
    case 'current_posts':
      $block['subject'] = t('Current posts');
      if (user_access('access content')) {
        // Retrieve and process data here.
      }
  }
}

function custom_block_2_menu() {
  $items = array();

  $items['admin/config/content/custom_block_2'] = array(
    'title' => 'Custom Block 2',
    'description' => 'Configuration for Current posts module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('custom_block_2_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
